### PR TITLE
Updated gpuv.json - Added 5 by 5 steps and excluded really high and l…

### PR DESCRIPTION
**Pull request by sauliiin**
…ow values, that probably are not used

### CODE REVIEW

**Comment by sauliiin** [comment]
Sorry! One value missing:
Btw, the hex are correct and refer to gpu voltages and the file was tested
    {
        "name": "600mV",
        "hex": "580200"
    },

**Comment by kapez92** [comment]
hi, have you tested the changed values ​​yourself? is everything working successfully?

**Comment by sauliiin** [comment]
Sorry for the delay!
Yep! I made a commit, tested and using them right now. Everything is fine! Btw, Im not an expert, but I know my way around underhand packages, if you guys need any hep, I would gladly do it. aw some stuff that could be improved!

On the other hand, I couldn't make custom table to work. Tryed some stuff, but it failed, not sure if it is compatible with the kip, al least for mariko.


    Em quarta-feira, 5 de junho de 2024 às 04:17:00 BRT, kapez92 ***@***.***> escreveu:  
 
 


hi, have you tested the changed values ​​yourself? is everything working successfully?

**Comment by kapez92** [comment]
Thanks a lot! We will be glad for any help if you wish

**Pull request merged**
